<%@ Page Title="Rules and Regulations of RPG" Language="C#" MasterPageFile="~/templates/1-Col.master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="RolePlayersGuild.TOU.Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <meta name="description" content="We never want to limit your writing creativity, but to make this a better community, we do have some rules..." />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FullCol" runat="server">
    <p>Roleplayersguild.com Terms of Use Agreement<br />
        Effective Date: August 25, 2016</p>
    <p>Thank you for visiting the Roleplayersguild.com website. The Roleplayersguild.com website, as well as its associated content and services (hereinafter &ldquo;Website&rdquo;), is owned or operated by Villanite Enterprises (hereinafter &ldquo;Villanite Enterprises&rdquo;). Villanite Enterprises has adopted this Terms of Use Agreement (hereinafter &ldquo;Agreement&rdquo;) to govern your use of the Website and to define your rights and duties in using the Website.</p>
    <p>THIS AGREEMENT CONTAINS IMPORTANT INFORMATION ABOUT YOUR RIGHTS AND DUTIES IN USING THE WEBSITE AND YOU ARE ADVISED TO READ IT. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS CONTAINED WITHIN THIS AGREEMENT, YOU MUST IMMEDIATELY DISCONTINUE YOUR USE OF THE WEBSITE.</p>
    <p>VILLANITE ENTERPRISES RESERVES THE RIGHT TO MODIFY, SUSPEND, DISCONTINUE, SELL, OR REPLACE THE WEBSITE AT ANY TIME, WITHOUT NOTICE, AND IN ITS SOLE DISCRETION. VILLANITE ENTERPRISES FURTHER RESERVES THE RIGHT TO MODIFY, SUSPEND, DISCONTINUE, AMEND, OR REPLACE THIS AGREEMENT AT ANY TIME, WITHOUT NOTICE, AND IN ITS SOLE DISCRETION. YOUR USE OF THE WEBSITE AFTER A MODIFICATION, AMENDMENT, OR REPLACEMENT OF THIS AGREEMENT CONSTITUTES YOUR MANIFESTATION OF INTENT TO SAID MODIFICATION, AMENDMENT, OR REPLACEMENT.</p>
    <p>Representations and Warranties</p>
    <p>Use of the Website is void where prohibited. You represent and warrant that you have the right, power, and legal capacity to enter into this Agreement and to accept the duties and rights granted in it. You represent and warrant that you are the age of 13 or older and that you will, in good faith, comply with the terms of this Agreement. You are expressly prohibited from using the Website outside of the uses explicitly stated in this Agreement and from using the Website in violation of any applicable law or regulation anywhere in the world. You agree to comply with all applicable local, national, and international laws, treaties, and regulations.</p>
    <p>Grant of Limited License</p>
    <p>The Website, including but not limited to the text, software, scripts, graphics, photos, sounds, music, videos, interactive features, and trademarks contained therein, is the property of Villanite Enterprises and is protected by all applicable laws, intellectual property or otherwise. The Website may not be used, modified, copied, distributed, framed, reproduced, crawled, aggregated, reverse engineered, republished, downloaded, scraped, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without the prior written consent of Villanite Enterprises. The foregoing prohibition on crawling and aggregation will not apply to search engines or non-commercial and publicly available archives that appropriately comply with Villanite Enterprises&rsquo;s robots.txt file.</p>
    <p>Villanite Enterprises hereby grants you a limited, non-exclusive, non-sub licensable, royalty free, non-assignable, and revocable license to use the Website for your personal and non-commercial use. You are expressly prohibited from reproducing, modifying, distributing, publishing, licensing, creating derivative works of, selling, publicly displaying, or publicly performing the Website outside of the uses expressly stated in this Agreement.</p>
    <p>Member Accounts</p>
    <p>Villanite Enterprises may provide you with the ability to register a member account, which may provide you with access to additional areas and features of the Website that are not accessible to non-members (hereinafter &ldquo;Member Account&rdquo;). Your Member Account is protected by a username and password. You acknowledge that you are solely responsible for maintaining the security and confidentiality of your username and password and for any access to your Member Account, whether authorized or unauthorized. In the event your Member Account is accessed without your authorization, you agree to immediately provide notice to Villanite Enterprises.</p>
    <p>You have a duty to ensure that the information that you provide through your Member Account is truthful, current, complete, and accurate. You understand and agree that you have an ongoing duty to update and keep current the information provided through your Member Account if and when that information changes. You are expressly prohibited from creating a Member Account that impersonates another person, contains offensive or obscene language, or otherwise violates the rights of a third party. You expressly agree that you will not register more than one Member Account and that you will not use your Member Account to interfere with or disrupt a third party&rsquo;s enjoyment and use of the Website. Villanite Enterprises reserves the right to restrict access to, suspend, disable, or delete your Member Account at any time, in its sole discretion, and without prior warning. You are expressly prohibited from selling, leasing, lending, assigning, or otherwise transferring your Member Account.</p>
    <p>By creating a Member Account, you expressly agree that Villanite Enterprises may contact you by any available means, including but not limited to by email.</p>
    <p>User Generated Content</p>
    <p>Villanite Enterprises may allow you to create user generated content through or to upload user generated content to the Website, including but not limited to photographs, videos, sound files, profile information, text, and biographical information (hereinafter &ldquo;User Generated Content&rdquo;). Villanite Enterprises does not claim any ownership rights in your User Generated Content and, should you submit User Generated Content to the Website, you retain ownership of your User Generated Content subject to the non-exclusive license granted to Villanite Enterprises herein. You hereby provide Villanite Enterprises with a non-exclusive, irrevocable, sublicensable, worldwide, perpetual, and royalty-free license to reproduce, prepare derivative works of, distribute copies of, perform publicly, and display publicly any and all User Generated Content that you submit to the Website in any form and for any and all purposes of the Website.</p>
    <p>You represent and warrant that you own any and all User Generated Content that you create through or upload to the Website, that your User Generated Content will not violate the rights of third parties, including but not limited to privacy rights, publicity rights, intellectual property rights, or other proprietary rights, that your User Generated Content will fully comply with the terms of this Agreement, and that your User Generated Content does not violate any applicable law or regulation anywhere in the world.</p>
    <p>Term</p>
    <p>This Agreement will remain in full force and effect until otherwise terminated pursuant to the terms of this Agreement. Villanite Enterprises reserves the right to remove, edit, deny, restrict, reject, or refuse any User Generated Content submitted through your Member Account.</p>
    <p>Third Party Links</p>
    <p>The Website may contain links to third party content and websites that are not owned or controlled by Villanite Enterprises. You acknowledge and agree that Villanite Enterprises is not responsible and cannot be held liable for third party content and Websites.</p>
    <p>Prohibited Activity</p>
    <p>You are expressly prohibited, through your use of the Website, from violating any law, statute, ordinance, regulation, or treaty, from violating the rights of a third party, and from using the Website outside of its customary and intended uses. More specifically (but without limitation), you are expressly prohibited from:</p>
    <p>1. Harassing, stalking, or threatening other users or third parties;</p>
    <p>2. Using a robot, spider, scraper, or other automated technology to access the Website;</p>
    <p>3. Imposing a disproportionate load on the Website or its server infrastructure or otherwise attempting to interfere with the operation of the Website;</p>
    <p>4. Framing the services or otherwise falsely suggesting a relationship with, the sponsorship of, or the approval of Villanite Enterprises;</p>
    <p>5. Circumventing the Website&rsquo;s copy protection measures or security technologies;</p>
    <p>6. Posting or transmitting content that threatens or encourages bodily harm or destruction of property;</p>
    <p>7. Posting or transmitting content that infringes upon the intellectual property rights of other users or third parties;</p>
    <p>8. Posting or transmitting content that is defamatory, invasive, obscene, pornographic, or offensive;</p>
    <p>9. Posting or transmitting content that incites racism, hatred, or bigotry;</p>
    <p>10. Posting or transmitting content that contains nudity or links to adult websites;</p>
    <p>11. Posting or transmitting content that constitutes fraud, an unwanted commercial solicitation, a phishing scam, a pyramid scheme, or a chain letter;</p>
    <p>12. Posting or transmitting content that promotes or aids in criminal activity;</p>
    <p>13. Posting or transmitting content that contains viruses, spyware, adware, or other malicious or harmful code;</p>
    <p>14. Posting or transmitting content that constitutes false advertising, including but not limited to a violation of Part 255 of the FTC&rsquo;s false advertising regulations; and</p>
    <p>15. Posting or transmitting content intended to collect personal or personally identifiable information from users or third parties.</p>
    <p>Interactive Computer Service</p>
    <p>The Website is an &ldquo;interactive computer service&rdquo; as those terms are defined under Section 230 of the Communications Decency Act. Though Villanite Enterprises undertakes commercially reasonable efforts to ensure that your experience of the Website is safe and enjoyable, you use the Website at your own risk. Though Villanite Enterprises will not be treated as the publisher or speaker of any tortious content posted to the Website, Villanite Enterprises reserves the right to remove any content from the Website that it determines is offensive, unlawful, threatening, defamatory, obscene, or otherwise objectionable, which will be determined in Villanite Enterprises&rsquo;s sole and absolute discretion.</p>
    <p>Indemnification</p>
    <p>You expressly agree to defend, indemnify, and hold harmless Villanite Enterprises, its parents, subsidiaries, partners, affiliates, directors, officers, employees, shareholders, managers, vendors, independent contractors, agents, successors, and assigns, from and against any and all claims, costs (including attorneys&rsquo; fees), damages, liabilities, judgments, and expenses of any kind arising out of or related to (1) your use or misuse of the Website; (2) your breach of any term or condition of this Agreement, (3) your violation of any applicable law, regulation, statute, treaty, or ordinance, or (4) your violation of the rights of a third party. Villanite Enterprises retains the right to exclusively control and direct its defense of any claim, cost, damage, liability, judgment, or expense subject to indemnification. You duty to defend, indemnify, and hold harmless Villanite Enterprises will survive the expiration, termination, or failure of this Agreement.</p>
    <p>Disclaimer of Warranties</p>
    <p>VILLANITE ENTERPRISES DISCLAIMS ANY RESPONSIBILITY FOR ANY HARM OR LIABILITY ARISING OUT OF OR RELATED TO YOUR USE OF THE WEBSITE, INCLUDING BUT NOT LIMITED TO PERSONAL INJURY. VILLANITE ENTERPRISES PROVIDES THE WEBSITE ON AN AS-IS BASIS AND WITH NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, NON-INFRINGEMENT, OR QUALITY. SOME JURISDICTIONS DO NOT ALLOW AN EXCLUSION OF IMPLIED WARRANTIES. IF YOU ARE LOCATED IN SUCH A JURISDICTION, THIS EXCLUSION MAY NOT APPLY.</p>
    <p>Limitation of Liability</p>
    <p>YOU UNDERSTAND AND AGREE THAT VILLANITE ENTERPRISES WILL NOT BE LIABLE TO YOU ON ANY LEGAL THEORY FOR ANY AND ALL DAMAGES THAT ARISE OUT OF THE USE AND LICENSE OF THE WEBSITE, INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS, LOSS OF INCOME, SPECIAL DAMAGES, INCIDENTAL DAMAGES, CONSEQUENTIAL DAMAGES, PUNATIVE DAMAGES, OR EXEMPLARY DAMAGES. YOU UNDERSTAND AND AGREE THAT VILLANITE ENTERPRISES WILL ONLY BE LIABLE TO YOU FOR THE AMOUNT PAID FOR THE WEBSITE, AND IN NO CASE WILL THAT AMOUNT EXCEED $1,000. IF NO AMOUNT IS PAID BY YOU TO VILLANITE ENTERPRISES, YOU AGREE THAT YOU WILL BE LIMITED TO INJUNCTIVE RELIEF ONLY UNLESS OTHERWISE PERMITTED BY LAW.</p>
    <p>SOME STATES OR PROVINCES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF DAMAGES. IF YOUR STATE OR PROVINCE DOES NOT ALLOW THE EXCLUSION OR LIMITATION OF DAMAGES, YOU SHOULD SEEK LEGAL COUNSEL TO UNDERSTAND YOUR LEGAL RIGHTS UNDER THE LAW OF YOUR STATE.</p>
    <p>Indemnification</p>
    <p>You understand and agree that you will hold harmless and indemnify Villanite Enterprises, including its members, agents, successors, assigns, independent contractors, and employees, from and against any and all claims, demands, damages, obligations, losses, liabilities, costs or debts, and expenses, including but not limited to attorneys&rsquo; fees, that arise from your use of or access to the Website, your violation of any term or condition of this Agreement, your violation of the rights of a third party, or your violation of any applicable law, statute, regulation, ordinance, or treaty, whether local, state, provincial, national, or international. This obligation to hold harmless and indemnify Villanite Enterprises will survive the failure or termination of this Agreement or your use of the Website.</p>
    <p>Assignment</p>
    <p>You hereby understand and agree that you are prohibited from assigning your rights and obligations under this Agreement. Villanite Enterprises may assign its rights and obligations under this Agreement at any time, including but not limited to in a sale of the Website.</p>
    <p>Resolution of Disputes</p>
    <p>This Agreement will be interpreted under and governed by the laws of the State of Arizona without giving effect to any conflicts of laws principles. You agree that any claim or dispute that you may have against Villanite Enterprises will be exclusively resolved through arbitration.</p>
    <p>YOU AND VILLANITE ENTERPRISES AGREE THAT ARBITRATION WILL BE THE EXCLUSIVE FORUM AND REMEDY AT LAW FOR ANY DISPUTES ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE WEBSITE, INCLUDING ANY DISPUTES CONCERNING THE VALIDITY, INTERPRETATION, VIOLATION, BREACH, OR TERMINATION OF THIS AGREEMENT. ARBITRATION UNDER THIS AGREEMENT WILL BE HELD IN PINAL COUNTY, ARIZONA AND WILL BE HELD IN ACCORDANCE WITH THE MOST RECENTLY EFFECTIVE COMMERCIAL ARBITRATION RULES RELEASED BY THE AMERICAN ARBITRATION ASSOCIATION. THE ARBITRATOR WILL HAVE THE DISCRETION AND AUTHORITY TO AWARD COSTS AND ATTORNEYS&rsquo; FEES TO THE PREVAILING PARTY AND WILL DECIDE THE ARBITRATION PROCEEDING UNDER THE LEGAL PRINCIPLES AND LAWS OF THE STATE OF ARIZONA. THE LOSING PARTY WILL BE REQUIRED TO PAY THE PREVAILING PARTY&rsquo;S REASONABLE ATTORNEYS&rsquo; FEES. YOU AND VILLANITE ENTERPRISES AGREE THAT BOTH PARTIES WILL BE REQUIRED TO BE PRESENT WITHIN THE STATE OF ARIZONA IN ORDER TO PERFORM THEIR OBLIGATIONS UNDER THIS AGREEMENT. YOU AND VILLANITE ENTERPRISES AGREE TO SUBMIT TO THE PERSONAL JURISDICTION OF ANY SUCH ARBITRATOR OR ARBITRATION PROCEEDING.</p>
    <p>Privacy Policy</p>
    <p>Villanite Enterprises hereby incorporates its Privacy Policy by reference.</p>
    <p>Additional Terms</p>
    <p>A finding that any term or provision of this Agreement is invalid or unenforceable will not affect the validity or enforceability of this Agreement. Any term or provision of this Agreement that is found to be invalid or unenforceable will be reformed to the extent necessary to make it valid and enforceable.</p>
    <p>You understand and agree that no term or provision of this Agreement will be deemed to have been waived and no breach will be deemed to have been consented to unless said waiver or consent is in writing and signed by the party to be charged.</p>
    <p>You understand and agree that included with the terms of this Agreement, you are expect understand and adhere to any other rules provided provided on this website.</p>
    <p>This Agreement and the Privacy Policy incorporated by reference constitute the entire agreement between you and Villanite Enterprises with respect to the Website. You understand and agree that there are no further understandings, agreements, or representations with respect to the Website that are not specified in this Agreement. You understand and agree that any additional provisions that may appear in any communication from you will not bind Villanite Enterprises.</p>
    <p>The Website is not directed to persons under the age of eightteen (18) and Villanite Enterprises will not knowingly collect personally identifiable information from children under the age of eightteen (18). If Villanite Enterprises inadvertently collects personally identifiable information, Villanite Enterprises will delete the personally identifiable information in accordance with its security protocols.</p>
    <p>VILLANITE ENTERPRISES AND YOU BOTH AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE WEBSITE MUST COMMENCE WITHIN ONE YEAR AFTER THE CAUSE OF ACTION ACCRUES. FAILURE TO ASSERT SAID CAUSE OF ACTION WITHIN ONE YEAR WILL PERMANENTLY BAR ANY AND ALL RELIEF.</p>
    <p>All rights not expressly granted herein are reserved to Villanite Enterprises.</p>
</asp:Content>
